name: blackhole
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  app_links: ^6.4.0
  audio_service: ^0.18.12
  audiotagger: ^2.2.1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  dart_des: ^1.0.2
  device_info_plus: ^11.3.0
  # ffmpeg_kit_flutter_audio: ^6.0.3
  file_picker: ^9.0.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_lyric:
    path: ./flutter_lyric
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # home_widget: ^0.3.0
  # html_unescape: ^2.0.0
  just_audio: ^0.9.36
  logging: ^1.2.0
  marquee: ^2.2.3
  material_design_icons_flutter: ^7.0.7296
  media_store_plus: ^0.1.3
  metadata_god: ^0.5.2+1
  on_audio_query: ^2.9.0
  package_info_plus: ^8.3.0
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  persistent_bottom_nav_bar: ^6.2.1
  receive_sharing_intent: 1.6.7
  share_plus: ^10.1.4
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.2.4
  # uuid: ^3.0.7
  # workmanager: ^0.5.1
  youtube_explode_dart: ^2.3.5

  http: any
  audio_session: any
  rxdart: any
dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  msix: ^3.16.7
  dependency_validator: ^5.0.0
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Medium.otf
          weight: 600

msix_config:
  display_name: Singularity
  publisher_display_name: Ankit Sangwan
  identity_name: org.xf.singularity
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
