[package]
name = "rust_lib_singularity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"

reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }